apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brain.fullname" . }}-config
data:
  config.yaml: |
    port: {{ .Values.config.port }}
    contentDir: {{ .Values.config.contentDir | quote }}
    hostKeyPath: {{ .Values.config.hostKeyPath | quote }}
    {{- with .Values.config.authorizedKeys }}
    authorizedKeys:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    updateTasks: {{ .Values.config.updateTasks }}

  {{- with .Values.config.mkdocsConfig }}
  mkdocs.yaml:
    {{- toYaml . | nindent 4 }}
  {{- end }}